import { useState, useEffect, useCallback } from "react";
import WizardStepIndicator from "./WizardStepIndicator";
import Step1InfoGeneral from "./Step1InfoGeneral";
import Step2Sedes from "./Step2Sedes";
import Step3Usuarios from "./Step3Usuarios";
import Step4Contactos from "./Step4Contactos";
import Step5Portal from "./Step5Portal";
import type {
  WizardData,
  EmpresaGeneralData,
  UsuarioData,
  ContactoAdminConfig,
  ContactoTecnicoConfig,
  ResponsableSedeConfig,
} from "./wizardTypes";
import { createEmpresa, updateEmpresa, crearWizard } from "../../services/empresasService";

interface CreateEmpresaWizardProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

const STEPS = [
  { number: 1, label: "Info General" },
  { number: 2, label: "Sedes" },
  { number: 3, label: "Usuarios" },
  { number: 4, label: "Contactos" },
  { number: 5, label: "Portal" },
];

const initialWizardData: WizardData = {
  general: {
    nombre: "",
    ruc: "",
    codigoCliente: "",
    direccionFiscal: "",
    direccionOperativa: "",
    ciudad: "",
    provincia: "",
    sector: "",
    paginaWeb: "",
    observacionesGenerales: "",
  },
  sedes: [],
  usuarios: [],
  contactosAdmin: [],
  contactosTecnicos: [],
  responsablesSede: [],
  contrasenaPortalSoporte: "",
};

const CreateEmpresaWizard = ({ isOpen, onClose, onSuccess }: CreateEmpresaWizardProps) => {
  const [currentStep, setCurrentStep] = useState(1);
  const [wizardData, setWizardData] = useState<WizardData>({ ...initialWizardData });
  const [loading, setLoading] = useState(false);
  const [createdInfo, setCreatedInfo] = useState<null | { codigoCliente?: string; usuario?: string; contrasena?: string }>(null);
  const [error, setError] = useState<string | null>(null);

  // Note: `codigoCliente` is generated by backend. Do not generate locally here.

  // Reset when closed
  useEffect(() => {
    if (!isOpen) {
      setCurrentStep(1);
      setWizardData({ ...initialWizardData });
      setError(null);
    }
  }, [isOpen]);

  // Step navigation
  const goNext = useCallback(() => setCurrentStep(prev => Math.min(prev + 1, 5)), []);
  const goPrev = useCallback(() => setCurrentStep(prev => Math.max(prev - 1, 1)), []);

  // === Data setters ===
  const setGeneral = (data: EmpresaGeneralData) => {
    setWizardData(prev => ({ ...prev, general: data }));
  };

  const handleSedeAdded = (sede: SedeData) => {
    setWizardData(prev => ({ ...prev, sedes: [...prev.sedes, sede] }));
  };

  const handleSedeRemoved = (idx: number) => {
    setWizardData(prev => ({ ...prev, sedes: prev.sedes.filter((_, i) => i !== idx) }));
  };

  const handleUsuarioCreated = (usuario: UsuarioData) => {
    setWizardData(prev => ({ ...prev, usuarios: [...prev.usuarios, usuario] }));
  };

  const handleUsuarioRemoved = (idx: number) => {
    setWizardData(prev => ({ ...prev, usuarios: prev.usuarios.filter((_, i) => i !== idx) }));
  };

  const setContactosAdmin = (contactos: ContactoAdminConfig[]) => {
    setWizardData(prev => ({ ...prev, contactosAdmin: contactos }));
  };

  const setContactosTecnicos = (contactos: ContactoTecnicoConfig[]) => {
    setWizardData(prev => ({ ...prev, contactosTecnicos: contactos }));
  };

  const setResponsablesSede = (responsables: ResponsableSedeConfig[]) => {
    setWizardData(prev => ({ ...prev, responsablesSede: responsables }));
  };

  const setContrasena = (value: string) => {
    setWizardData(prev => ({ ...prev, contrasenaPortalSoporte: value }));
  };



  // === Final submit: use transactional wizard endpoint if available ===
  const handleFinalSubmit = async () => {
    setLoading(true);
    setError(null);
    try {
      // Build payload with tempIds for sedes and usuarios
      const payload = {
        nombre: wizardData.general.nombre,
        ruc: wizardData.general.ruc,
        direccionFiscal: wizardData.general.direccionFiscal,
        direccionOperativa: wizardData.general.direccionOperativa,
        ciudad: wizardData.general.ciudad,
        provincia: wizardData.general.provincia,
        sector: wizardData.general.sector,
        paginaWeb: wizardData.general.paginaWeb,
        observaciones: wizardData.general.observacionesGenerales,
        contrasenaPortalSoporte: wizardData.contrasenaPortalSoporte,
        sedes: wizardData.sedes.map(s => ({
          tempId: String(s._id || s.id || s.tempId || ""),
          nombre: s.nombre,
          codigoInterno: s.codigoInterno,
          direccion: s.direccion,
          ciudad: s.ciudad,
          provincia: s.provincia,
          telefono: s.telefono,
          email: s.email,
          tipo: s.tipo,
          horarioAtencion: s.horarioAtencion,
          observaciones: s.observaciones,
        })),
        usuarios: wizardData.usuarios.map(u => ({
          tempId: String(u._id || u.id || u.tempId || ""),
          sedeId: u.sedeId,
          nombreCompleto: u.nombreCompleto,
          correo: u.correo,
          cargo: u.cargo,
          telefono: u.telefono,
          observaciones: u.observaciones,
          tipoDocumento: u.tipoDocumento,
          numeroDocumento: u.numeroDocumento,
        })),
        contactosAdmin: wizardData.contactosAdmin.map(ca => ({
          usuarioId: ca.usuarioId,
          nombre: ca.nombreCompleto,
          autorizacionFacturacion: ca.autorizacionFacturacion,
        })),
        contactosTecnicos: wizardData.contactosTecnicos.map(ct => ({
          usuarioId: ct.usuarioId,
          nombre: ct.nombreCompleto,
          horarioDisponible: ct.horarioDisponible,
          contactoPrincipal: ct.contactoPrincipal,
          autorizaCambiosCriticos: ct.autorizaCambiosCriticos,
          supervisionCoordinacion: ct.supervisionCoordinacion,
          nivelAutorizacion: ct.nivelAutorizacion,
        })),
        responsablesSede: wizardData.responsablesSede.map(r => ({
          sedeId: r.sedeId,
          usuarioId: r.usuarioId,
          autorizaIngresoTecnico: r.autorizaIngresoTecnico,
          autorizaMantenimientoFueraHorario: r.autorizaMantenimientoFueraHorario,
          supervisionCoordinacion: r.supervisionCoordinacion,
        })),
      };

      // Call transactional endpoint
      const resp = await crearWizard(payload as Parameters<typeof crearWizard>[0]);

      // Map tempId -> realId from response if present
      const sedeIdMap: Record<string, string> = {};
      if (Array.isArray(resp?.sedes)) {
        for (const s of resp.sedes) {
          const temp = String(s?.tempId || "");
          const real = String(s?._id || s?.id || "");
          if (temp && real) sedeIdMap[temp] = real;
        }
      }
      const usuarioIdMap: Record<string, string> = {};
      if (Array.isArray(resp?.usuarios)) {
        for (const u of resp.usuarios) {
          const temp = String(u?.tempId || "");
          const real = String(u?._id || u?.id || "");
          if (temp && real) usuarioIdMap[temp] = real;
        }
      }

      // Optionally: you could update local state with real IDs here.
      // Show generated codigoCliente/credenciales to user
      const codigo = resp?.empresa?.codigoCliente || resp?.codigoCliente || resp?.empresa?.codigoCliente || resp?.codigoCliente;
      const usuario = resp?.credenciales?.usuario || resp?.empresa?.credenciales?.usuario || undefined;
      const contrasena = resp?.credenciales?.contrasena || resp?.empresa?.credenciales?.contrasena || undefined;
      setCreatedInfo({ codigoCliente: codigo ? String(codigo) : undefined, usuario, contrasena });
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      const responseErr = (err as { response?: { data?: { error?: string; empresaExistente?: string } } })?.response;
      if (responseErr?.data?.error?.includes?.("RUC")) {
        const empresa = responseErr.data.empresaExistente || "otra empresa";
        setError(`Este RUC ya está registrado en "${empresa}". Verifica el RUC.`);
      } else {
        setError(responseErr?.data?.error || errMsg || "Error al crear la empresa");
      }
    } finally {
      setLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-3xl max-h-[92vh] flex flex-col overflow-hidden">
        {/* Header */}
        <div className="sticky top-0 bg-white border-b px-6 pt-6 pb-4 z-10">
          <div className="flex items-center justify-between mb-5">
            <h2 className="text-xl font-bold text-gray-900">Crear Nueva Empresa</h2>
            <button
              type="button"
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <WizardStepIndicator steps={STEPS} currentStep={currentStep} />
        </div>

        {/* Error banner */}
        {error && (
          <div className="mx-6 mt-4 bg-red-50 border-l-4 border-red-500 rounded-lg p-4 flex items-start gap-3">
            <svg className="w-5 h-5 text-red-600 mt-0.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <div className="flex-1">
              <p className="text-sm text-red-700">{error}</p>
            </div>
            <button type="button" onClick={() => setError(null)} className="text-red-400 hover:text-red-600">
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {currentStep === 1 && (
            <Step1InfoGeneral
                data={wizardData.general}
                onChange={setGeneral}
                onNext={goNext}
              />
          )}

          {currentStep === 2 && (
            <Step2Sedes
              sedes={wizardData.sedes}
              onSedeAdded={handleSedeAdded}
              onSedeRemoved={handleSedeRemoved}
              onNext={goNext}
              onPrev={goPrev}
            />
          )}

          {currentStep === 3 && (
            <Step3Usuarios
              usuarios={wizardData.usuarios}
              sedes={wizardData.sedes}
              onUsuarioCreated={handleUsuarioCreated}
              onUsuarioRemoved={handleUsuarioRemoved}
              onNext={goNext}
              onPrev={goPrev}
            />
          )}

          {currentStep === 4 && (
            <Step4Contactos
              usuarios={wizardData.usuarios}
              sedes={wizardData.sedes}
              contactosAdmin={wizardData.contactosAdmin}
              contactosTecnicos={wizardData.contactosTecnicos}
              responsablesSede={wizardData.responsablesSede}
              onContactosAdminChange={setContactosAdmin}
              onContactosTecnicosChange={setContactosTecnicos}
              onResponsablesSedeChange={setResponsablesSede}
              onNext={goNext}
              onPrev={goPrev}
            />
          )}

          {currentStep === 5 && (
            <Step5Portal
              ruc={wizardData.general.ruc}
              contrasena={wizardData.contrasenaPortalSoporte}
              onContrasenaChange={setContrasena}
              onPrev={goPrev}
              onSubmit={handleFinalSubmit}
              loading={loading}
            />
          )}
        </div>
        {createdInfo && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
            <div className="bg-white rounded-2xl shadow-xl max-w-md w-full p-5 border">
              <h4 className="text-lg font-bold mb-2">Empresa creada</h4>
              <p className="text-sm text-slate-700 mb-3">Código de cliente: <span className="font-mono font-bold">{createdInfo.codigoCliente}</span></p>
              {createdInfo.usuario && <p className="text-sm text-slate-600">Usuario: <span className="font-mono">{createdInfo.usuario}</span></p>}
              {createdInfo.contrasena && <p className="text-sm text-slate-600 mb-3">Contraseña: <span className="font-mono">{createdInfo.contrasena}</span></p>}
              <div className="mt-4 flex justify-end gap-2">
                <button onClick={() => setCreatedInfo(null)} className="px-4 py-2 rounded-lg bg-white border text-slate-700">Cerrar</button>
                <button onClick={() => { setCreatedInfo(null); onSuccess(); onClose(); }} className="px-4 py-2 rounded-lg bg-blue-600 text-white">Aceptar</button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default CreateEmpresaWizard;
